Add request_number rule
mockoon/commons-server pull request #5
Opened 2021-04-27 17:44 UTC by davidvieiratrustly

**Parent issue** 
https://github.com/mockoon/mockoon/issues/459

Closes https://github.com/mockoon/mockoon/issues/459

**Technical implementation details**

Implement a new 'request_number' as described on the issue.

2021-04-29 13:17 UTC, 255kb requested changes

2021-04-29 13:17 UTC, 255kb commented on src/libs/response-rules-interpreter.ts
> +      .reduce((a,b) => (a > b) ? a : b, 0);
This could be simplified to avoid 4 iterations:

```suggestion
      .reduce((max, response) => Math.max(...[max, ...response.rules.flatMap(rule =>rule.target==='request_number' ?[parseInt(rule .value, 10)] : 0)]), 0)
```

2021-04-29 13:17 UTC, 255kb commented on src/libs/response-rules-interpreter.ts
> +      return (requestNumber % maxRequestNumber) === Number.parseInt(rule.value, 10) - 1;
I think this should be update to supports the regex option, so users can easily create range rules like: 
`^[1-9][0-9]?$|^100$` --> requests between 1 to 100

2021-04-29 13:24 UTC, davidvieiratrustly commented on src/libs/response-rules-interpreter.ts
> +      return (requestNumber % maxRequestNumber) === Number.parseInt(rule.value, 10) - 1;
The issue with regex is that I don't know how many requests can be processed to be able to loop through it.

That's why I did remove the regex support for this rule.

2021-04-29 13:25 UTC, davidvieiratrustly commented on src/libs/response-rules-interpreter.ts
> +      return (requestNumber % maxRequestNumber) === Number.parseInt(rule.value, 10) - 1;
What do you think?

2021-04-29 13:27 UTC, davidvieiratrustly commented on src/libs/response-rules-interpreter.ts
> +      .reduce((a,b) => (a > b) ? a : b, 0);
It is showing this error with this code TS2339: Property 'flatMap' does not exist on type 'ResponseRule[]'.

2021-04-29 13:27 UTC, davidvieiratrustly commented on src/libs/response-rules-interpreter.ts
> +      .reduce((a,b) => (a > b) ? a : b, 0);
It's a false alarm?

2021-04-29 13:32 UTC, 255kb commented on src/libs/response-rules-interpreter.ts
> +      return (requestNumber % maxRequestNumber) === Number.parseInt(rule.value, 10) - 1;
ok, I just saw that when testing the app. I guess it makes sense to disabled the regex option in order to be able to loop.

2021-04-29 13:35 UTC, 255kb commented on src/libs/response-rules-interpreter.ts
> +      .reduce((a,b) => (a > b) ? a : b, 0);
ah no, it's not. We should then target es2019, only thing, I just saw that flatMap is only compatible with Node.js >=11. So for now we could revert to a reduce. 
But I still think you can get rid of the first `map` and last `reduce`, by using a `Math.max(...)` with spread operator.

2021-05-03 09:34 UTC, 255kb approved these changes

2021-05-03 09:40 UTC, merged