Add baseUrl Request Helper
mockoon/commons-server pull request #8
Opened 2021-05-06 15:03 UTC by louiealmeda

Computed baseUrl

**Parent issue** 

Closes #7 

**Technical implementation details**

* Added `baseUrl` to RequestHelpers
* Added `Environment` as a required parameter for `TemplateParser` and `RequestHelpers`
* Updated all unit tests for `TemplateParser` to set the `Environment` as `null`
* Added unit tests for building the `baseUrl`

2021-05-06 15:05 UTC, louiealmeda commented on src/libs/server.ts
> +            }/${declaredRoute.endpoint.replace(/ /g, '%20')}`;
no changes here, but linter automatically formatted this.

2021-05-06 15:30 UTC, louiealmeda commented
Hmmm.. lints are failing, I'll check tomorrow.

2021-05-07 06:25 UTC, 255kb commented
Yes, you need to use prettier for formatting, it's mandatory. Easiest is to use the VSCode/Webstorm extension, but you could also do a `npx prettier --write`.

2021-05-07 08:25 UTC, 255kb commented on src/libs/server.ts
> +            }/${declaredRoute.endpoint.replace(/ /g, '%20')}`;
it needs to be re-formatted with Prettier, probably it will revert the change.

2021-05-07 08:41 UTC, 255kb requested changes
Thanks for the PR, it looks great 👍 
Maybe my idea of allowing `null` for the environment wasn't that good, we should use `{} as any` in the tests, so we don't have to allow `Environment | null` in the `TemplateParser` just for them. Could you please make the changes? 
Sorry for the extra work.

2021-05-07 08:41 UTC, 255kb commented on src/libs/templating-helpers/request-helpers.ts
> +export const RequestHelpers = function (request: Request, environment: Environment | null) {
Remove `null`.

2021-05-07 08:41 UTC, 255kb commented on test/template-parser.spec.ts
> +      const parseResult = TemplateParser("{{concat 'test' 'test'}}", {} as any, null);
Use `{} as any` in all test cases instead of `null`

2021-05-07 08:41 UTC, 255kb commented on test/template-parser.spec.ts
> +    });
Port should/will never be undefined in an environment, so this case will never happens. What are you trying to achieve?

2021-05-07 08:41 UTC, 255kb commented on test/template-parser.spec.ts
> +    });
Isn't this duplicated with a previous case "should return correct url format without port" line 681?

2021-05-07 10:36 UTC, louiealmeda commented on test/template-parser.spec.ts
> +    });
Ahh I see. Hmmm, I'm thinking about what would happen if the request was forwarded through an API gateway or router 🤔

2021-05-07 10:39 UTC, louiealmeda commented on test/template-parser.spec.ts
> +    });
Yeah, it seems like it. I wanted to isolate the test case for ensuring the the hostname is correctly being picked up. Not sure what to do with "should return correct url format without port" yet though..

2021-05-07 12:29 UTC, louiealmeda commented on test/template-parser.spec.ts
> +    });
I removed handling of undefined port and the related test case

2021-05-07 12:30 UTC, louiealmeda commented on test/template-parser.spec.ts
> +    });
`should return correct url format without port` test case is removed

2021-05-07 13:38 UTC, louiealmeda commented on src/libs/templating-helpers/request-helpers.ts
> +      const prefix = !!environment.endpointPrefix
Alright, removing the forced boolean conversion

2021-05-07 13:55 UTC, 255kb commented
Thanks! I will take care of the documentation and integrate the lib in the next release.

2021-05-07 13:55 UTC, merged